### ISSUE TITLE
八橋検校は39歳

### ISSUE THREAD

**Issue by Hirokazu-Murayama** [ReiA-O/project-_of_B3#1]
八橋検校でsh39でsh。留学と退学を繰り返shてここに来ました。よろしくお願いしまsh。好きな言葉はshriiiiiiiiineとmushroooooooooooomでsh。

**Comment by tututu12321** [comment]
電気電子工学科は婚活訓練予備校ch
@DofE123E 理系中堅大学出身。電気電子工学を学ぼう、数3や高校物理ができなくても電電に入れる。国立大に入学できなかったら私立理系に共通テストを利用して入学しよう。国立大への志望者も電電に進学しよう。男性なら技術者としてのエンジニアリングスキルが非常に重要であり、女性なら希少価値の高い人材としてチヤホヤされることでしょう。
